import numpy as np
import numpy_clustering_functions as ncf

"""
DO NOT EDIT THIS FILE
"""


def run_tests():
    """
    Runs a series of tests for clustering-related functions to validate their implementation.

    The function performs various tests on the custom clustering-related functions, assessing
    their availability, implementation status, and output correctness. It utilizes labeled
    test cases, a set of dummy data, and preconfigured parameters to verify the behavior
    of those functions. The function also reports the results of each test in a tabular
    format, showing the function status as implemented, missing, or producing an error.

    :return: None
    :rtype: NoneType
    """
    np.random.default_rng(0)

    # 1. Set up small test data
    dummy_data = np.array([[1.0, 2.0], [1.4, 1.8], [5.0, 8.0], [8.0, 8.0], [6.5, 8.0]])
    dummy_centers = np.array([[1.2, 1.9], [6.5, 8.0]])
    dummy_ids = np.array([0, 0, 1, 1, 1])

    # List of functions to test: (function_object, arguments_tuple, label)
    tests = [
        (ncf.generate_normal_random_group, (np.array([0, 0]), np.array([1, 1]), 5), "Normal Random Group", (5,2)),
        (ncf.generate_uniform_random_group, (np.array([0, 0, 0]), np.array([1, 1, 2]), 5), "Uniform Random Group", (5,3)),
        (ncf.min_max_normalize, (dummy_data,), "Min-Max Normalization", []),
        (ncf.compute_distance_to_centers, (dummy_data, dummy_centers), "Distance to Centers",[]),
        (ncf.assign_data_to_cluster, (dummy_data, dummy_centers), "Assign Data to Cluster",[]),
        (ncf.compute_cluster_centers, (dummy_data, dummy_ids), "Compute Cluster Centers",[]),
        (ncf.intra_cluster_distance, (dummy_data, dummy_ids, dummy_centers), "Intra-cluster Distance",[]),
        (ncf.inter_cluster_distance, (dummy_data, dummy_ids, dummy_centers), "Intra-cluster Distance",[]),
        (ncf.clustering_initialisation_by_assignment, (dummy_data, 2), "Cluster assignment", []),
        (ncf.clustering_initialisation_by_selection, (dummy_data, 2), "Cluster selection", []),
        (ncf.leader_clustering, (dummy_data, 3.0), "Leader Clustering",[]),
        (ncf.kmeans_clustering, (dummy_data, 2, 5), "K-Means Clustering",[]),
    ]

    print(f"{'Function Name':<30} | {'Status':<15}")
    print("-" * 50)

    for func, args, label, expected in tests:
        try:
            # Check if the function exists in the module
            if not hasattr(ncf, func.__name__):
                print(f"{label:<30} | MISSING")
                continue

            result = func(*args)

            if result is None:
                print(f"{label:<30} | WARNING: Not Implemented")
            else:
                print(f"{label:<30} | IMPLEMENTED (Output Type: {type(result).__name__})")
                print(result)

        except Exception as e:
            print(f"{label:<30} | ERROR: {str(e)}")
        print()


if __name__ == "__main__":
    run_tests()

